version: '3'
services:
  db:
    image: mysql:5.7.22
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "4306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./mysqlconf:/etc/mysql/conf.d
  web:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/qiitan
      - bundle-install:/usr/local/bundle
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: ""
      DATABASE_HOSTNAME: db
      DATABASE_NAME: qiitan
    tty: true
volumes:
  db-data:
  bundle-install:
